apiVersion: metrics.tekton.dev/v1alpha1
kind: PipelineMonitor
metadata:
  name: team
spec:
  pipelineName: hello-everyone
  metrics:
  # default running gauge
  - name: status # tekton_metrics_task_release_status
    type: gauge
    by:
    - condition: "Succeeded"
    - label: team
