apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller
  namespace: tekton-metrics-operator
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-metrics-operator
