kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: controller-cluster-access
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-metrics-operator
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["taskruns", "pipelineruns", "task", "pipeline"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["metrics.tekton.dev"]
    resources: ["taskmonitors", "taskrunmonitors", "pipelinemonitors", "pipelinerunmonitors"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  # Controller needs cluster access to leases for leader election.
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: controller-cluster-access
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-metrics-operator
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: tekton-metrics-operator
roleRef:
  kind: ClusterRole
  name: controller-cluster-access
  apiGroup: rbac.authorization.k8s.io

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: controller
  namespace: tekton-metrics-operator
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-metrics-operator
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
    resourceNames: ["config-logging", "config-observability", "config-leader-election"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: controller
  namespace: tekton-metrics-operator
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-metrics-operator
subjects:
  - kind: ServiceAccount
    name: controller
    namespace: tekton-metrics-operator
roleRef:
  kind: Role
  name: controller
  apiGroup: rbac.authorization.k8s.io
