apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: taskmonitors.metrics.tekton.dev
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-metrics-operator
    pipeline.tekton.dev/release: "devel"
    version: "devel"
spec:
  group: metrics.tekton.dev
  scope: Namespaced
  names:
    kind: TaskMonitor
    plural: taskmonitors
    singular: taskmonitor
    shortNames:
    - tm
    categories:
    - tektonmonitors
    - tekton
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: taskrunmonitors.metrics.tekton.dev
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-metrics-operator
    pipeline.tekton.dev/release: "devel"
    version: "devel"
spec:
  group: metrics.tekton.dev
  scope: Namespaced
  names:
    kind: TaskRunMonitor
    plural: taskrunmonitors
    singular: taskrunmonitor
    shortNames:
    - trm
    categories:
    - tektonmonitors
    - tekton
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pipelinemonitors.metrics.tekton.dev
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-metrics-operator
    pipeline.tekton.dev/release: "devel"
    version: "devel"
spec:
  group: metrics.tekton.dev
  scope: Namespaced
  names:
    kind: PipelineMonitor
    plural: pipelinemonitors
    singular: pipelinemonitor
    shortNames:
    - pm
    categories:
    - tektonmonitors
    - tekton
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pipelinerunmonitors.metrics.tekton.dev
  labels:
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-metrics-operator
    pipeline.tekton.dev/release: "devel"
    version: "devel"
spec:
  group: metrics.tekton.dev
  scope: Namespaced
  names:
    kind: PipelineRunMonitor
    plural: pipelinerunmonitors
    singular: pipelinerunmonitor
    shortNames:
    - prm
    categories:
    - tektonmonitors
    - tekton
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
